### ISSUE TITLE
noplyr version!

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/Rsampling#12]
I just finished and "committed" a new version of Rsampling without any *plyr function. The speed improved a lot.  All new functions has the same structure and logic as "plyr" version. I tested the shiny UI and seems that everthing is OK!  With this version we have no packages dependences.... Please, test it! The branch name is noplyr. 
To install this version:
library(devtools)
install_github(repo = 'lageIBUSP/Rsampling', ref = "noplyr")

**Comment by adalardo** [comment]
I did not create a pull request to this new version. IT is better people test it before!

**Comment by andrechalom** [comment]
The speedup from using `for()` is amazing! I think we may be able to increase the selectors in the interface by one order of magnitude.

**Comment by adalardo** [comment]
I had the same thought. yes, lets increase...

**Comment by andrechalom** [comment]
I'll do that after we merge this branch.

**Comment by piklprado** [comment]
Wow! FasteR, cleaneR, strongeR!
I tested with the examples of the vignettes with Rsampling-shiny and also running the same examples in the command line. See PR #15

**Comment by andrechalom** [comment]
> Rule 3. Fancy algorithms are slow when n is small, and n is usually small. Fancy algorithms have big constants. Until you know that n is frequently going to be big, don't get fancy.
> (Rob Pyke, Notes on C Programming)
