### ISSUE TITLE
Add 'fix zeroes' funcionality

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling#2]
Resampling stats allows to keep cells with zeroes fixed while the others are shuffled/resampled.
Check how to include this option in Rsampling.

**Comment by piklprado** [comment]
Probably easier to now with the code without plyr

**Comment by andrechalom** [comment]
Added on PR #20

**Comment by andrechalom** [comment]
OK, the question remains on: can / should / how to include this in rows_as_units / columns_as_units? If we decide this can't / shouldn't be included, I think we should close this issue.

**Comment by piklprado** [comment]
I think it is ok by now. Closing, but see enhancement #22
