### ISSUE TITLE
Include fixed zeroes functionality in vignetes

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling#22]
See PR #20

**Comment by andrechalom** [comment]
I think the updated vignettes should mark a major release version for the package (v1.0?) and a submission to CRAN.

**Comment by piklprado** [comment]
Sure, I added the translation of vignettes (#24) as a milestone.

**Comment by andrechalom** [comment]
Are the zero-fixed examples in the vignettes now? I couldn't find them.

**Comment by andrechalom** [comment]
Opening the issue again as I could not find the examples. Will wait feedback from @piklprado as maybe he included the examples but did not push them to github?

**Comment by piklprado** [comment]
No, I did not yet. A simple task, but I am including it in the v1.0 milestone
