### ISSUE TITLE
Send to CRAN?

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/Rsampling#25]
Sending this project to CRAN will make installation easier, and might increase the usage by other researchers. When should we do it?

**Comment by piklprado** [comment]
So far all that separate us from releasing v1.0 are the related issues #22 and #24. September and mid-October are realy hectic for me and probably I won't have time to do that now. But if @andrechalom or @adalardo would like do do this please feel free.

**Comment by adalardo** [comment]
I have no time available until november too! If  @andrechalom can not work on issues #22 and #24 too, our best scenario is send to CRAN in november/december.

**Comment by andrechalom** [comment]
Hi. I am unable to help on #22 as I don't have the neccessary background
knowledge. I could work on #24, but I'm having trouble installing the
required tools.

**Comment by piklprado** [comment]
PR #28 has a version that passed `devtools::check()`. Please let me know if we can release this.

**Comment by andrechalom** [comment]
There is a "mini-issue" on the vignettes: the footnotes are being formatted in a somewhat weird way. We're using [^1] , and something along the pipeline is interpreting this as "[^(1])", so the closing brace is superscript but the opening is not
