### ISSUE TITLE
Allow variable size in resampling

### ISSUE THREAD

**Issue by piklprado** [lageIBUSP/Rsampling#3]
Resampling Stats allows that the sample size resulting from resampling can larger or smaller than the original data. Check if/how to include that in Rsampling.

**Comment by andrechalom** [comment]
With the new _plyrless_ implementation, this seems easy to implement.

**Comment by andrechalom** [comment]
Added this functionality to rows/cols_as_units (see #17). Please let me know if you think this should be included in any of the other rand types.

**Comment by andrechalom** [comment]
Merged and working as intended. Should we close this issue?
