### ISSUE TITLE
Why we should keep the original logic of Resampling Stats Excel plugin?

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/Rsampling#4]
In ResStat Excel logic the data can be shifted by columns or rows in order to embrace paired/block experimental design. If we are creating a new tool for students who have no stats skills, my suggestion is use one data structure to input that is coherent with R and with good data analysis practices.

**Comment by piklprado** [comment]
I agree that we can recommend a tidy data structure and provide functions to resample tidy data. But because tidy data are not familiar for beginners I think we should  keep also options to randomize the more traditional structures.

**Comment by andrechalom** [comment]
I believe we can work on a tutorial (EcoVirtual style) that guides the students from common questions to the most adequate data table structure. The tutorial can be referenced in the Rsampling help and/or interfaces, but I believe it is outside the scope of the Rsampling package - as its goal is explicitly to be a free replacement for ResStat.
