### ISSUE TITLE
Author list cites Fulano

### ISSUE THREAD

**Issue by andrechalom** [lageIBUSP/Rsampling#5]
Is he really involved in the project?
![fulano](https://cloud.githubusercontent.com/assets/1994997/8387937/26f3b1a8-1c33-11e5-90b7-330ca6a6d38b.jpg)

**Comment by piklprado** [comment]
Who's this guy????

Hope your names be in the place of this impostor in the next pull requests
:)

2015-06-26 18:43 GMT-03:00 andrechalom notifications@github.com:

> Is he really involved in the project?
> [image: fulano]
> https://cloud.githubusercontent.com/assets/1994997/8387937/26f3b1a8-1c33-11e5-90b7-330ca6a6d38b.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lageIBUSP/Rsampling/issues/5.

## 

*Paulo Inácio de Knegt López de Prado
*Depto. de Ecologia - Instituto de Biociências -
USPhttp://ecologia.ib.usp.br/let http://ecologia.ib.usp.br/get
Rua do Matão, travessa 14, nº 321
Cid. Universitária, São Paulo - SP - Brasil
CEP 05508-900
+55-11-30910963 (sala)
+55-11-30917600 (Secretaria)
